### ISSUE TITLE
Command and Contact definition examples

### ISSUE THREAD

**Issue by aaronrosenbergNSMG** [akadoya/nagios-msteams#1]
Is there anyway you can provide command and contact examples?

**Comment by akadoya** [comment]
You can place this script any where you want in nagios server but here is my environment's example.

command:
```
define command {
	command_name                   	notify-teams
	command_line                   	$USER1$/nagios-msteams.pl --webhook 'https://outlook.office.com/webhook/xxxx/IncomingWebhook/xxx/xxx --nagios_url 'http://my_nagios_server_url'
	register                       	1
}
```

contact:
```
define contact {
	contact_name                   	my_teams
	alias                          	MS teams integration
	host_notifications_enabled     	1
	service_notifications_enabled  	1
	host_notification_period       	24x7
	service_notification_period    	24x7
	host_notification_options      	d,r
	service_notification_options   	w,c,r,f,s
	host_notification_commands     	notify-teams
	service_notification_commands  	notify-teams
	pager                          	<my_tenant_id_in_teams>
	register                       	1
	}
```

**Comment by akadoya** [comment]
closing this

**Comment by picoroma** [comment]
Hi!
I'm trying to create command on ICINGA2 but seems that the scripts do not recognize the ICINGA variable.
Message are sent but are more or less empty.

**Comment by akadoya** [comment]
> Hi!
> I'm trying to create command on ICINGA2 but seems that the scripts do not recognize the ICINGA variable.
> Message are sent but are more or less empty.

Probably similar reason to #2 
Please check ICINGA2 macros definitions and you would need to map those macros to Nagios environment variables.
