### ISSUE TITLE
Empty notification when used on Centreon

### ISSUE THREAD

**Issue by jorkirico** [akadoya/nagios-msteams#10]
Hello,

We've just discover this plugin, and we're tryinh to do it work on Centreon. 

The notification is sent, but no information on it:

![Captura de pantalla 2024-01-11 164603](https://github.com/akadoya/nagios-msteams/assets/156342105/6afdf535-d4f8-4cc8-b6de-232e101922fd)

It wold be great if the variables sent on the notification could be specified as option field when executing the script.

**Comment by akadoya** [comment]
The plugin reads the information through the environment variables that are
exposed by the engine.
Nagios core exports NAGIOS_, inciga does ICINGA_ and those 2 prefixes are
the only ones supported by this script right now.

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/macros.html#:~:text=Macros%20as%20Environment%20Variables,made%20available%20as%20environment%20variables
.

Looking at Centreon's documentation, it seems like they do support the same
macro as NAGIOS prefixed environment variables.
They have this toggle configuration to enable it and I wonder if your
environment may be missing this flag?
https://github.com/centreon/centreon-engine/blob/d62b4d00a32536f63ab11a7d6d48093f4e96e7ed/conf/centengine.cfg.in#L997

**Comment by jorkirico** [comment]
Hello,

Thank you for your help. As soon as we've enabled the Environment Variables, it works as a charm
