### ISSUE TITLE
Use of uninitialized value $nagios

### ISSUE THREAD

**Issue by DanielGrankvist** [akadoya/nagios-msteams#2]
Hi. 

Getting this when I run the command, anything I'm missing? 

Use of uninitialized value $nagios{"SERVICESTATE"} in string at ./nagios-msteams.pl line 64.
Use of uninitialized value $nagios{"HOSTALIAS"} in concatenation (.) or string at ./nagios-msteams.pl line 65.
Use of uninitialized value $nagios{"SERVICESTATE"} in concatenation (.) or string at ./nagios-msteams.pl line 65.
Use of uninitialized value $nagios{"HOSTALIAS"} in string at ./nagios-msteams.pl line 67.
Use of uninitialized value $nagios{"SERVICEOUTPUT"} in string at ./nagios-msteams.pl line 67.
Use of uninitialized value in concatenation (.) or string at ./nagios-msteams.pl line 79.

**Comment by akadoya** [comment]
I guess you are just running the script on your terminal without setting nagios environment variables.
If you like to test that way, check the samples in read me and export nagios environment variables first. https://github.com/akadoya/nagios-msteams#usage
when the script is run through nagios, nagios process will pass those environment variables when it kicks notification commands.

**Comment by DanielGrankvist** [comment]
If I set the variable it works. But not when i run it from Nagios (OP5). Same result with empty data.

**Comment by akadoya** [comment]
that's because OP5 can use Nagios macros but doesn't send Nagios environment variables as bare Nagios core does.
here are some workaround you can take.
http://www.naemon.org/documentation/usersguide/macros.html#macros_as_environment_variables

**Comment by DanielGrankvist** [comment]
Ah i see. Thank you!

**Comment by bertieuk** [comment]
Note: Nagios 4 (v4.3.4 from Ubuntu repo - installed on Ubuntu 20.02.1 LTS) by default has environment variables disabled. Took me ~3 hours to work this out, and the parameter _enable_environment_macros_ in nagios.cfg needs changing to 1.

**Comment by ar0431** [comment]
I am trying to use this but could not find how to provide environment variables. I do not know how many environment variable your script need. Can you please tell me how to provide these variables in NagiosXI? Or maybe you can pull all the required variables in your script?

**Comment by akadoya** [comment]
> I am trying to use this but could not find how to provide environment variables. I do not know how many environment variable your script need. Can you please tell me how to provide these variables in NagiosXI? Or maybe you can pull all the required variables in your script?

nagiosXI uses, nagios core4, right?
Nagios core internally sets those env vars so you shouldn't have to do anything.
See more details in [here](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/macros.html) Macros as Environment Variables and Available Macros sections are relevant.
If they are not set, you may want to check the configuration that @bertieuk mentioned above.

**Comment by ar0431** [comment]
That is true, NagioXI uses nagios core4. But script is not giving the alert
for Downtime. It just giving host status is up or not. I am looking for
"Downtime" alert.

Regards,
Syed Rizvi
ph#716-525-0382

**Comment by danielhamelberg** [comment]
@ar0431 In your contact, host and service [definitions](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/objectdefinitions.html#contact), see that the applicable notification option is set to send notifications when host or service scheduled downtime starts and ends.

**Comment by ar0431** [comment]
Daniel, thanks for reply. But when scheduled downtime starts and ends, this script send the following message. So its mean that contact, host and service definitions are correct. But the content of the message is not correct. It should say " Downtime started for the host" not "host status is up".

---/host status is UP
Host Notes:

Host:	


Details:	
OK -  rta 0.086ms lost 0%

Note:- I remove the host name for the security reason. So ignore the host name.
